### PR TITLE
Compat 8.14

### PR DESCRIPTION
**Pull request by liyishuai**
Disable native compiler which just fails (don't know why).

### CODE REVIEW

**Comment by Lysxia** [comment]
I would rather avoid cppo. Since this is just a config it can be done more simply in the Makefile or as a shell script.

The error I'm getting is that `NSimpleIO_IO_Monad` is missing, and I have to explicitly enable the `-native-compiler` flag to get it. So perhaps the actual problem is that simple-io is not installing some files?

**Comment by liyishuai** [comment]
I have little knowledge on native compiler to locate the issue.

**Comment by Lysxia** [comment]
Do you run into this problem when you build coq-itree-io normally? (I don't)

**Comment by liyishuai** [comment]
Only failed on macOS. Ubuntu builds were fine.

**Comment by Lysxia** [comment]
Why is CI failing at the "Checkout code" step

**Comment by liyishuai** [comment]
I have no idea on that. Never seen it elsewhere.

**Comment by Lysxia** [comment]
Resetting the deploy key fixed it.

**Pull request merged**
